# Copyright (c) 2020 The University of Manchester
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

name: Python Actions
on: [push]
env:
  CODE_PATHS: examples python_models8 nmt_integration_tests

jobs:
  build:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        python-version: [3.6, 3.7, 3.8, 3.9]
    steps:
    # Check out the code and critical support code
    - name: Checkout
      uses: actions/checkout@v2
    - name: Checkout SupportScripts
      uses: actions/checkout@v2
      with:
        repository: SpiNNakerManchester/SupportScripts
        path: support

    # Set up the dependencies for everything
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install pip, etc
      uses: ./support/actions/python-tools
    - name: Install matplotlib
      uses: ./support/actions/install-matplotlib
    - name: Install Spinnaker Dependencies
      uses: ./support/actions/checkout-spinn-deps
      with:
        repositories: >
          SpiNNUtils SpiNNMachine SpiNNMan PACMAN DataSpecification spalloc
          SpiNNFrontEndCommon sPyNNaker TestBase
        install: true
    - name: Setup
      uses: ./support/actions/run-setup

    # Testing
    - name: Create a spynnaker.cfg
      uses: ./support/actions/configure-spynnaker
      with:
        board-address: spinn-4.cs.man.ac.uk
    - name: Run unit tests
      run: |
        if [ -d unittests ]; then
            pytest unittests
        else
            echo "::warning::No unit tests defined"
        fi

    # Code quality assessment
    - name: Lint with flake8
      run: flake8 $CODE_PATHS

    - name: Lint with pylint
      uses: ./support/actions/pylint
      with:
        package: ${{ env.CODE_PATHS }}

    - name: Run rat copyright enforcement
      if: matrix.python-version == 3.8
      uses: ./support/actions/check-copyrights

    - name: Validate all XML
      if: matrix.python-version == 3.8
      uses: ./support/actions/validate-xml
      with:
        base-path: ${{ env.CODE_PATHS }}
